### ISSUE TITLE
iSCSIDaemon does not compile on Mavericks (10.9) asl_* not defined

### ISSUE THREAD

**Issue by BjoKaSH** [iscsi-osx/iSCSIInitiator#30]
The userland daemon iSCSIDaemon does not compile on Mavericks. It fails in the logging part:
```
iSCSIInitiator/Source/User Tools/iSCSIDaemon.c:1260:5: error: unknown type name 'asl_object_t'; did you mean 'io_object_t'?
    asl_object_t log = asl_open(NULL,NULL,ASL_OPT_STDERR);
    ^~~~~~~~~~~~
```

According to ```man asl```on a Mavericks box, ```asl_open()``` returns (and other functions expect) the type ```aslclient``` in OS X 10.9.

**Comment by nsinenian** [comment]
The weird thing is that my man page (El Capitan) uses asl_object_t, while some of the other docs use aslclient. Strange.
